//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CitasAgendadas
    {
        public int idCita { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public string MotivoCita { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> Empresaid { get; set; }
        public Nullable<int> Usuarioid { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual Login Login { get; set; }
    }
}
