//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clientes()
        {
            this.HosCitasAgendadas = new HashSet<HosCitasAgendadas>();
            this.HosConsultas = new HashSet<HosConsultas>();
            this.HosRecetasyExamenes = new HashSet<HosRecetasyExamenes>();
        }
    
        public int idcliente { get; set; }
        public string nombre { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tel { get; set; }
        public string cel { get; set; }
        public string ciudad { get; set; }
        public string sector { get; set; }
        public string calle { get; set; }
        public string casa { get; set; }
        public string estado { get; set; }
        public string ocupacion { get; set; }
        public string credito { get; set; }
        public string idcuenta { get; set; }
        public string idcuentacxc { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<decimal> credito_usado { get; set; }
        public string mayorista { get; set; }
        public Nullable<int> idgarante { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string cedula { get; set; }
        public string direccion { get; set; }
        public string observacion { get; set; }
        public string email { get; set; }
        public string web { get; set; }
        public Nullable<System.DateTime> fecha_nac { get; set; }
        public Nullable<int> idnacion { get; set; }
        public string beneficiario { get; set; }
        public Nullable<int> idciudad { get; set; }
        public Nullable<int> idClasificacion { get; set; }
        public Nullable<decimal> montoAprobado { get; set; }
        public Nullable<decimal> MoraPorciento { get; set; }
        public Nullable<decimal> MoraDias { get; set; }
        public Nullable<decimal> puntos { get; set; }
        public Nullable<int> idoficial { get; set; }
        public Nullable<int> idpersona { get; set; }
        public string idpreferencial { get; set; }
        public Nullable<int> idncf { get; set; }
        public Nullable<decimal> limitexdia { get; set; }
        public Nullable<int> idvendedor { get; set; }
        public Nullable<int> idreferido { get; set; }
        public Nullable<byte> referidor { get; set; }
        public Nullable<byte> sexo { get; set; }
        public Nullable<int> estadoCivil { get; set; }
        public string AseguradoNombre { get; set; }
        public string AseguradoTel { get; set; }
        public string AseguradoDir { get; set; }
        public Nullable<System.DateTime> AseguradofechaNac { get; set; }
        public Nullable<int> AseguradoParentezco { get; set; }
        public Nullable<byte> AseguradoSexo { get; set; }
        public string tel2 { get; set; }
        public Nullable<int> idseguro1 { get; set; }
        public Nullable<int> idseguro2 { get; set; }
        public string contratoNo1 { get; set; }
        public string contratoNo2 { get; set; }
        public string GrupoNo1 { get; set; }
        public string GrupoNo2 { get; set; }
        public string GrupoNombre1 { get; set; }
        public string GrupoNombre2 { get; set; }
        public string NombreTarjeta1 { get; set; }
        public string NombreTarjeta2 { get; set; }
        public Nullable<int> deducible1 { get; set; }
        public Nullable<int> deducible2 { get; set; }
        public Nullable<System.DateTime> fechaComienza1 { get; set; }
        public Nullable<System.DateTime> fechaComienza2 { get; set; }
        public Nullable<System.DateTime> fechaExpira1 { get; set; }
        public Nullable<System.DateTime> fechaExpira2 { get; set; }
        public Nullable<int> idseguro3 { get; set; }
        public string contratoNo3 { get; set; }
        public string GrupoNo3 { get; set; }
        public string GrupoNombre3 { get; set; }
        public string NombreTarjeta3 { get; set; }
        public Nullable<int> deducible3 { get; set; }
        public Nullable<System.DateTime> fechaComienza3 { get; set; }
        public Nullable<System.DateTime> fechaExpira3 { get; set; }
        public Nullable<byte> nacimiento { get; set; }
        public Nullable<byte> documento { get; set; }
        public string NSSPoliza { get; set; }
        public string tutor { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> Usuarioid { get; set; }
        public string Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosCitasAgendadas> HosCitasAgendadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosConsultas> HosConsultas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosRecetasyExamenes> HosRecetasyExamenes { get; set; }
        public virtual HosLogin HosLogin { get; set; }
    }
}
