//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Consultas
    {
        public int idConsulta { get; set; }
        public string TipoConsulta { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public string edad { get; set; }
        public string telefono { get; set; }
        public string SeguroMedico { get; set; }
        public string Compania { get; set; }
        public string Poliza { get; set; }
        public string Observaciones { get; set; }
        public string Diagnostico { get; set; }
        public string Receta { get; set; }
        public string Examenes { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> Empresaid { get; set; }
        public Nullable<int> Usuarioid { get; set; }
        public string Hora { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Login Login { get; set; }
    }
}
