//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosEspeciales
    {
        public int Id { get; set; }
        public Nullable<int> IdDatosEspeciales { get; set; }
        public string Valor { get; set; }
        public Nullable<int> Usuarioid { get; set; }
        public Nullable<int> idpaciente { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> idConsulta { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual especiales especiales { get; set; }
        public virtual Login Login { get; set; }
    }
}
