//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hosespeciales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hosespeciales()
        {
            this.HosDatosEspeciales = new HashSet<HosDatosEspeciales>();
            this.HosDetalleTemporales = new HashSet<HosDetalleTemporales>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> usuarioid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosDatosEspeciales> HosDatosEspeciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosDetalleTemporales> HosDetalleTemporales { get; set; }
        public virtual HosEmpresa HosEmpresa { get; set; }
        public virtual HosLogin HosLogin { get; set; }
    }
}
