//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HosLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HosLogin()
        {
            this.HosCitasAgendadas = new HashSet<HosCitasAgendadas>();
            this.Hosciudad = new HashSet<Hosciudad>();
            this.HosConsultas = new HashSet<HosConsultas>();
            this.HosDatosEspeciales = new HashSet<HosDatosEspeciales>();
            this.Hosespeciales = new HashSet<Hosespeciales>();
            this.HosHistoriaClinica = new HashSet<HosHistoriaClinica>();
            this.HosRecetasyExamenes = new HashSet<HosRecetasyExamenes>();
            this.Hospaciente = new HashSet<Hospaciente>();
            this.clientes = new HashSet<clientes>();
        }
    
        public int LoginId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Privilegio { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> empresaid { get; set; }
        public Nullable<int> estatus { get; set; }
        public string Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosCitasAgendadas> HosCitasAgendadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosciudad> Hosciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosConsultas> HosConsultas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosDatosEspeciales> HosDatosEspeciales { get; set; }
        public virtual HosEmpresa HosEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hosespeciales> Hosespeciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosHistoriaClinica> HosHistoriaClinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HosRecetasyExamenes> HosRecetasyExamenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospaciente> Hospaciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clientes> clientes { get; set; }
    }
}
