//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConsultaMedicasEntities : DbContext
    {
        public ConsultaMedicasEntities()
            : base("name=ConsultaMedicasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CitasAgendadas> CitasAgendadas { get; set; }
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<HistoriaClinica> HistoriaClinica { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<RecetasyExamenes> RecetasyExamenes { get; set; }
        public virtual DbSet<especiales> especiales { get; set; }
        public virtual DbSet<DatosEspeciales> DatosEspeciales { get; set; }
        public virtual DbSet<DetalleTemporales> DetalleTemporales { get; set; }
        public virtual DbSet<Consultas> Consultas { get; set; }
    
        public virtual int TemptoEspecial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TemptoEspecial");
        }
    
        public virtual int VaciarTablaTemporal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VaciarTablaTemporal");
        }
    
        public virtual ObjectResult<sp_reporte_examenes_back_Result> sp_reporte_examenes_back(Nullable<decimal> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_examenes_back_Result>("sp_reporte_examenes_back", idParameter);
        }
    
        public virtual ObjectResult<sp_reporte_HistorialClinico_back_Result> sp_reporte_HistorialClinico_back(Nullable<decimal> idConsulta)
        {
            var idConsultaParameter = idConsulta.HasValue ?
                new ObjectParameter("idConsulta", idConsulta) :
                new ObjectParameter("idConsulta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_HistorialClinico_back_Result>("sp_reporte_HistorialClinico_back", idConsultaParameter);
        }
    
        public virtual ObjectResult<sp_reporte_receta_back_Result> sp_reporte_receta_back(Nullable<decimal> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_receta_back_Result>("sp_reporte_receta_back", idParameter);
        }
    }
}
