//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class hospointEntities : DbContext
    {
        public hospointEntities()
            : base("name=hospointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HosCitasAgendadas> HosCitasAgendadas { get; set; }
        public virtual DbSet<Hosciudad> Hosciudad { get; set; }
        public virtual DbSet<HosConsultas> HosConsultas { get; set; }
        public virtual DbSet<HosDatosEspeciales> HosDatosEspeciales { get; set; }
        public virtual DbSet<HosDetalleTemporales> HosDetalleTemporales { get; set; }
        public virtual DbSet<HosEmpresa> HosEmpresa { get; set; }
        public virtual DbSet<Hosespeciales> Hosespeciales { get; set; }
        public virtual DbSet<HosHistoriaClinica> HosHistoriaClinica { get; set; }
        public virtual DbSet<HosLogin> HosLogin { get; set; }
        public virtual DbSet<HosRecetasyExamenes> HosRecetasyExamenes { get; set; }
        public virtual DbSet<Hospaciente> Hospaciente { get; set; }
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
    
        public virtual ObjectResult<sp_reporte_examenes_back_Result> sp_reporte_examenes_back(Nullable<decimal> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_examenes_back_Result>("sp_reporte_examenes_back", idParameter);
        }
    
        public virtual ObjectResult<sp_reporte_HistorialClinico_back_Result> sp_reporte_HistorialClinico_back(Nullable<decimal> idConsulta)
        {
            var idConsultaParameter = idConsulta.HasValue ?
                new ObjectParameter("idConsulta", idConsulta) :
                new ObjectParameter("idConsulta", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_HistorialClinico_back_Result>("sp_reporte_HistorialClinico_back", idConsultaParameter);
        }
    
        public virtual ObjectResult<sp_reporte_receta_back__Result> sp_reporte_receta_back_(Nullable<decimal> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_receta_back__Result>("sp_reporte_receta_back_", idParameter);
        }
    
        public virtual int TemptoEspecial()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TemptoEspecial");
        }
    
        public virtual int VaciarTablaTemporal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VaciarTablaTemporal");
        }
    
        public virtual int Predeterminado(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Predeterminado", idParameter);
        }
    }
}
