//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultaMedicasEntities : DbContext
    {
        public ConsultaMedicasEntities()
            : base("name=ConsultaMedicasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TipoConsulta> TipoConsulta { get; set; }
        public virtual DbSet<CitasAgendadas> CitasAgendadas { get; set; }
        public virtual DbSet<ciudad> ciudad { get; set; }
        public virtual DbSet<Consultas> Consultas { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<HistoriaClinica> HistoriaClinica { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<RecetasyExamenes> RecetasyExamenes { get; set; }
    }
}
