//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpointLiteVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paciente()
        {
            this.CitasAgendadas = new HashSet<CitasAgendadas>();
            this.Consultas = new HashSet<Consultas>();
            this.RecetasyExamenes = new HashSet<RecetasyExamenes>();
        }
    
        public int idPaciente { get; set; }
        public string nombre { get; set; }
        public string telefono { get; set; }
        public string telefono2 { get; set; }
        public Nullable<int> idciuddad { get; set; }
        public string cedula { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> Empresaid { get; set; }
        public Nullable<int> Usuarioid { get; set; }
        public string Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitasAgendadas> CitasAgendadas { get; set; }
        public virtual ciudad ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultas> Consultas { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Login Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetasyExamenes> RecetasyExamenes { get; set; }
    }
}
